version: "3.8"

services:
  backend:
    build:
      context: ./infra/docker/backend
      dockerfile: Dockerfile
      # うまくボリュームできない時コメントアウト
    # volumes:
    # - ./src/backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  frontend:
    build:
      context: ./infra/docker/frontend
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./infra/docker/db/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - db

volumes:
  db_data:
